4101:
  users_not_found:
    - "User does not exist:"
  Access denied for account:
    - "Access denied. Cannot modify another S3 account."
    - "Access denied."
4104:
  user_permission_denied:
    - "Cannot change roles for super user"
    - "Non super user cannot change roles for self"
    - "Cannot delete the last {} user"
    - "Normal user cannot delete other user"
  update_not_allowed:
    - "{} can not update the role for {}"
    - "{} can not update the password for {}"
    - "{} can not update the email id for {}"
    - "Cannot change role for the last {} user"
    - "{} can not update {}"
    - "Can not update role to admin"
  Cannot create other users:
    - "Only {} user can create other {} users"
  PermissionDenied:
    - 'Access to the requested resource is forbidden'
4099:
  invalid body msg_id:
    - "Invalid request body: {'bucket_name': [\"Bucket Name should be between 4-56 Characters long.Should contain either lowercase, numeric or '-' characters. Not starting or ending with '-'\"]}"
  invalid parameter msg_id:
    - "Invalid request body: {'password': [\"Password Policy Not Met. Must be more than 8 characters. Must contain at least one Uppercase Alphabet. Must contain at least one Lowercase Alphabet. Must contain at least one Numeric value. Must include !@#$%^&*()_+-=[]{}|'.\"]}"
    - "Invalid request body: {'password': ['Password Policy Not Met. Must contain at least one Numeric value.']}"
  invalid request parameter:
    - "username cannot be modified"
    - "Insufficient information in request body"
  Invalid parameter for user:
     - "{'sort_by': ['Must be one of: user_id, username, user_type, alert_notification, email, created_time, updated_time.']}":
     - "{'dir': ['Must be one of: desc, asc.']}":
     - "{'sortby': ['Must be one of: user_id, username, email, user_type, role, created_time, updated_time, email_address, user_role.']}":
  empty key:
    - "_schema: Empty value for access_key"
    - "_schema: Empty value for secret_key"
    - "Uid: Field may not be null."
    - "{}: Unknown field."
  InvalidKeyType:
    - "Invalid key type specified. Must be one of S3, shift"
    - "Max_buckets: Not a valid integer."
    - "Suspended: Not a valid boolean."
    - "Op_mask: Invalid value."
  MalformedRequest:
    - "{}: Must be one of: {}"
    - "{}: Field may not be null."
    - "{}: Not a valid integer."
    - "{}: Not a valid boolean."
    - "{}: Empty value for {}"
    - "{}: Invalid value."
    - "{}: Unknown field."
    - "Invalid request."
    - "Invalid request body: {'password': [\"Password Policy Not Met. Must be more than 8 characters. Must contain at least one Uppercase Alphabet. Must contain at least one Lowercase Alphabet. Must contain at least one Numeric value. Must include !@#$%^&*()_+-=[]{}|'.\"]}"
    - "Invalid request body: {'password': [\"Password Policy Not Met. Must be more than 8 characters. Must contain at least one Uppercase Alphabet. Must contain at least one Lowercase Alphabet. Must include !@#$%^&*()_+-=[]{}|'.\"]}"
    - "Invalid request body: {'password': [\"Password Policy Not Met. Must be more than 8 characters. Must contain at least one Uppercase Alphabet. Must contain at least one Numeric value. Must include !@#$%^&*()_+-=[]{}|'.\"]}"
    - "Invalid request body: {'role': ['Must be one of: admin, manage, monitor.']}"
    - "Invalid request body: {'role': ['Must be one of: admin, manage, monitor.'], 'password': [\"Password Policy Not Met. Must be more than 8 characters. Must contain at least one Uppercase Alphabet. Must contain at least one Lowercase Alphabet. Must include !@#$%^&*()_+-=[]{}|'.\"]}"
    - "Invalid request body: {'password': [\"Password Policy Not Met. Must be more than 8 characters. Must contain at least one Uppercase Alphabet. Must contain at least one Lowercase Alphabet. Must include !@#$%^&*()_+-=[]{}|'.\"], 'role': ['Must be one of: admin, manage, monitor.']}"
4103:
  users_already_exists:
    - "User already exists:"
4113:
  HttpError:
    - 'Unauthorized'
12288:
  EntityAlreadyExists:
    - "The request was rejected because it attempted to create an account that already exists."
    - 'Provided access key exists and belongs to another user.'
  NoSuchUser:
    - "User does not exist."
  KeyExists:
    - 'Provided access key exists and belongs to another user.'
  InvalidCapability:
    - "Attempt to grant invalid admin capability."
  UserAlreadyExists:
    - "Attempt to create existing user."
  EmailExists:
    - "Provided email address exists."
